# -*- coding: utf-8 -*-
"""Practica06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2CfgNQt0TJA7Mjuz_fcN42tVgUJtwkO

# Lab 06: ECDSA and ECDH (real world)
**Instituto Politécnico Nacional — ESCUELA SUPERIOR DE CÓMPUTO**  
Selected Topics in Cryptography — 24 de marzo de 2026  
Referencia: NIST SP800-186 + FIPS 186-5
"""

# ─────────────────────────────────────────────────────────────────
# IMPORTS
# ─────────────────────────────────────────────────────────────────
import base64
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import (
    decode_dss_signature,
    encode_dss_signature,
)
from cryptography.hazmat.primitives.kdf.concatkdf import ConcatKDFHash
from cryptography.exceptions import InvalidSignature

# ─────────────────────────────────────────────────────────────────
# CONSTANTES COMPARTIDAS
# Curvas sobre campo primo — NIST SP800-186 Sección 3.2.1
# Solo curvas Weierstrass sobre GF(p), tal como exige el lab.
# ─────────────────────────────────────────────────────────────────
curve_map = {
    "P-224": ec.SECP224R1(),
    "P-256": ec.SECP256R1(),
    "P-384": ec.SECP384R1(),
    "P-521": ec.SECP521R1(),
}

# Hash recomendado por FIPS 186-5 — la fortaleza del hash debe
# igualar o superar la fortaleza de seguridad de la curva.
HASH_FOR_CURVE = {
    "P-224": hashes.SHA224(),
    "P-256": hashes.SHA256(),
    "P-384": hashes.SHA384(),
    "P-521": hashes.SHA512(),
}

"""---
## Sección 1 — ECDSA con curvas estándar NIST
Basado en **NIST SP800-186** (parámetros de curva) y **FIPS 186-5** (algoritmo de firma).

| Función | Responsable |
|---|---|
| `generar_par_llaves` | Roberto |
| `firmar` | Roberto |
| `verificar` | **Hatziry** |
| `menu_ecdsa` | **Hatziry** |
"""

# ─────────────────────────────────────────────────────────────────
# 1.1 — Generación de par de llaves ECDSA
# Responsable: Roberto
# ─────────────────────────────────────────────────────────────────
def generar_par_llaves(archivo_priv, archivo_pub, curva_nombre="P-256"):
    """
    Genera un par de llaves ECDSA para la curva indicada.
    Guarda la llave privada y pública como base64 en archivos separados.
    """
    curva      = curve_map[curva_nombre]
    llave_priv = ec.generate_private_key(curva)
    llave_pub  = llave_priv.public_key()

    priv_der = llave_priv.private_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    pub_der = llave_pub.public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    with open(archivo_priv, "w") as f:
        f.write(base64.b64encode(priv_der).decode())
    with open(archivo_pub, "w") as f:
        f.write(base64.b64encode(pub_der).decode())

    print(f"[OK] Par de llaves generado ({curva_nombre})")
    print(f"     Privada → {archivo_priv}")
    print(f"     Pública → {archivo_pub}")

# ─────────────────────────────────────────────────────────────────
# 1.2 — Generación de firma ECDSA
# Responsable: Roberto
# ─────────────────────────────────────────────────────────────────
def firmar(archivo_priv, archivo_mensaje, archivo_firma, curva_nombre="P-256"):
    """
    Genera la firma ECDSA de un archivo usando la llave privada indicada.
    Guarda el par (r, s) en un archivo de texto.
    """
    with open(archivo_priv, "r") as f:
        priv_der = base64.b64decode(f.read().strip())
    llave_priv = serialization.load_der_private_key(priv_der, password=None)

    with open(archivo_mensaje, "rb") as f:
        mensaje = f.read()

    # La librería genera k seguro, calcula R=k·G, aplica H(m) y computa (r,s)
    firma_der = llave_priv.sign(mensaje, ec.ECDSA(HASH_FOR_CURVE[curva_nombre]))
    r, s = decode_dss_signature(firma_der)

    with open(archivo_firma, "w") as f:
        f.write(f"r={r}\ns={s}\n")

    print(f"[OK] Firma guardada en: {archivo_firma}")
    print(f"     r = {hex(r)}")
    print(f"     s = {hex(s)}")

# ─────────────────────────────────────────────────────────────────
# 1.3 — Verificación de firma ECDSA
# Responsable: Hatziry Vitales Herrera
# ─────────────────────────────────────────────────────────────────
def verificar(archivo_pub, archivo_mensaje, archivo_firma, curva_nombre="P-256"):
    """
    Verifica la firma ECDSA (FIPS 186-5, Sec. 6.4.2).

    Pasos internos del algoritmo:
      1. Valida r, s en [1, n-1]
      2. Calcula e = H(m)
      3. w = s^-1 mod n
      4. u1 = e*w mod n  ,  u2 = r*w mod n
      5. X = u1*G + u2*Q
      6. Compara v = x_X mod n  con r

    Parámetros:
        archivo_pub     — archivo con la llave pública en base64
        archivo_mensaje — archivo con el mensaje original (bytes)
        archivo_firma   — archivo de texto con r=... / s=...
        curva_nombre    — debe coincidir con la curva usada al firmar

    Retorna:
        True  si la firma es válida
        False si la firma NO es válida
    """

    # Paso 1 — Cargar llave pública desde base64
    with open(archivo_pub, "r") as f:
        pub_der = base64.b64decode(f.read().strip())
    llave_pub = serialization.load_der_public_key(pub_der)

    # Paso 2 — Leer mensaje original
    with open(archivo_mensaje, "rb") as f:
        mensaje = f.read()

    # Paso 3 — Leer r y s, reconstruir firma en formato DER
    r, s = None, None
    with open(archivo_firma, "r") as f:
        for linea in f:
            linea = linea.strip()
            if linea.startswith("r="):
                r = int(linea[2:])
            elif linea.startswith("s="):
                s = int(linea[2:])

    if r is None or s is None:
        raise ValueError("Archivo de firma inválido: no se encontraron r y/o s.")

    firma_der = encode_dss_signature(r, s)

    # Paso 4 — Verificar (pasos 2-6 ejecutados internamente por la librería)
    # Si la firma es válida, verify() termina sin error.
    # Si es inválida, lanza InvalidSignature.
    try:
        llave_pub.verify(firma_der, mensaje, ec.ECDSA(HASH_FOR_CURVE[curva_nombre]))
        print("[✓] Firma VÁLIDA — el mensaje no ha sido alterado.")
        return True
    except InvalidSignature:
        print("[✗] Firma INVÁLIDA — el mensaje fue alterado o la firma es incorrecta.")
        return False

# ─────────────────────────────────────────────────────────────────
# 1.4 — Menú / CLI principal
# Responsable: Hatziry Vitales Herrera
#
# Permite ejecutar UNA sola operación por llamada,
# tal como lo requiere el punto 1.4 del lab.
# ─────────────────────────────────────────────────────────────────
def menu_ecdsa():
    print("\n====== ECDSA — NIST SP800-186 / FIPS 186-5 ======")
    print("  1. Generar par de llaves")
    print("  2. Generar firma")
    print("  3. Verificar firma")
    opcion = input("Opción: ").strip()

    print(f"\nCurvas disponibles: {list(curve_map.keys())}")
    curva = input("Curva [P-256]: ").strip().upper() or "P-256"
    if curva not in curve_map:
        print("Curva no válida, usando P-256.")
        curva = "P-256"

    if opcion == "1":
        ap  = input("Nombre archivo llave privada: ").strip()
        apu = input("Nombre archivo llave pública:  ").strip()
        generar_par_llaves(ap, apu, curva)

    elif opcion == "2":
        ap = input("Archivo llave privada: ").strip()
        am = input("Archivo a firmar: ").strip()
        af = input("Archivo de salida para la firma: ").strip()
        firmar(ap, am, af, curva)

    elif opcion == "3":
        apu = input("Archivo llave pública: ").strip()
        am  = input("Archivo del mensaje: ").strip()
        af  = input("Archivo con la firma: ").strip()
        res = verificar(apu, am, af, curva)
        print(f"Resultado: {'VÁLIDA ✓' if res else 'INVÁLIDA ✗'}")

    else:
        print("Opción no reconocida.")

# ── Ejecutar el menú ECDSA ────────────────────────────────────────
menu_ecdsa()

"""---
## Sección 2 — ECDH con curvas estándar NIST
Basado en **NIST SP800-186** (parámetros de curva).  
Responsable: Emiliano
"""

# ─────────────────────────────────────────────────────────────────
# 2.2 — KDF basada en SHA-256 (familia SHA-2)
# NIST SP800-56A: Concat KDF con FixedInfo = AlgorithmID || PartyUInfo || PartyVInfo
# ─────────────────────────────────────────────────────────────────
def kdf(shared_secret_z, key_usage, entity_u, entity_v):
    # NIST: AlgorithmID || PartyUInfo || PartyVInfo
    fixed_info = key_usage + entity_u + entity_v
    ckdf = ConcatKDFHash(
        algorithm=hashes.SHA256(),
        length=32,           # 256 bits
        otherinfo=fixed_info # FixedInfo context
    )
    derived_key_k64 = base64.b64encode(ckdf.derive(shared_secret_z)).decode()
    return derived_key_k64

# ─────────────────────────────────────────────────────────────────
# 2.1 — Simulación de acuerdo de llaves ECDH
# Responsable: Emiliano
# ─────────────────────────────────────────────────────────────────
def simulate_diffie_hellman():
    print("\nAvailable NIST curves: P-224, P-256, P-384, P-521")
    select = input("Select a curve: ").strip().upper()
    while select not in curve_map:
        select = input("Invalid curve. Select a curve: ").strip().upper()
    curve = curve_map[select]

    select = input("Do you want to add FixedInfo? [0-No / Otherwise-Yes]: ")
    u_entity, v_entity, key_usage = b'', b'', b''
    if select != "0":
        u_entity  = (input("Enter User A identifier (e.g., Alice): ").strip() or "Alice").encode()
        v_entity  = (input("Enter User B identifier (e.g., Bob): ").strip() or "Bob").encode()
        key_usage = (input("Enter intended algorithm (e.g., AES-256-GCM): ").strip() or "AES-256-GCM").encode()

    # Generar llaves de Alice (a) y Bob (b)
    u_priv = ec.generate_private_key(curve)
    u_pub  = u_priv.public_key()
    v_priv = ec.generate_private_key(curve)
    v_pub  = v_priv.public_key()    # BUGFIX: era u_pub (copiaba la llave de Alice)

    # Serializar llaves públicas en PEM y guardar en archivos
    u_pub_pem = u_pub.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    v_pub_pem = v_pub.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    with open("aG_pub.pem", "wb") as f:
        f.write(u_pub_pem)
    with open("bG_pub.pem", "wb") as f:
        f.write(v_pub_pem)

    print(f"\n[aG] Llave pública de Alice (base64):\n{base64.b64encode(u_pub_pem).decode()}")
    print(f"\n[bG] Llave pública de Bob (base64):\n{base64.b64encode(v_pub_pem).decode()}")

    # Cada parte calcula el secreto compartido K = abG
    K  = u_priv.exchange(ec.ECDH(), v_pub)  # Alice: a * (bG)
    K2 = v_priv.exchange(ec.ECDH(), u_pub)  # Bob:   b * (aG)

    if K == K2:
        print("\n[✓] Secreto compartido igual en ambos lados (K == K2)")
    else:
        print("\n[✗] ERROR: los secretos no coinciden")

    print(f"\n[Step 1] Shared Secret K (Base64): {base64.b64encode(K).decode()}")
    print(f"[Step 2] Derived key k (256 bits, Base64): {kdf(K, key_usage, u_entity, v_entity)}")

# ── Ejecutar la simulación ECDH ───────────────────────────────────
simulate_diffie_hellman()